# Generated by Django 5.1.2 on 2025-01-15 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devtool", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Idea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_created=True, auto_now=True, verbose_name="수정일"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_created=True, auto_now_add=True, verbose_name="작성일"
                    ),
                ),
                ("title", models.CharField(max_length=20, verbose_name="아이디어명:")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="uploaded_images/%Y%m%d",
                        verbose_name="Image:",
                    ),
                ),
                ("content", models.TextField(verbose_name="아이디어 설명:")),
                ("interest", models.IntegerField(verbose_name="아이디어 관심도:")),
                (
                    "devtool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ideas",
                        to="devtool.tool",
                        verbose_name="예상 개발툴:",
                    ),
                ),
            ],
        ),
    ]
