# Generated by Django 5.1.2 on 2025-01-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideasite", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idea",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="posts/%Y%m%d", verbose_name="Image:"
            ),
        ),
    ]
