# Generated by Django 5.1.2 on 2025-01-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20, verbose_name="게시물 이름:")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="uploaded_images/%Y%m%d",
                        verbose_name="Image:",
                    ),
                ),
                ("description", models.TextField(verbose_name="게시물 내용:")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                ("like", models.IntegerField(default=0)),
            ],
        ),
    ]
