# Generated by Django 5.1.2 on 2025-01-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pirostagram", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="images/%Y%m%d", verbose_name="Image:"
            ),
        ),
    ]
