# Generated by Django 5.1.2 on 2025-01-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("year", models.TextField()),
                ("genre", models.TextField()),
                ("rating", models.TextField()),
                ("runtime", models.TextField()),
                ("review", models.TextField()),
                ("director", models.TextField()),
                ("actors", models.TextField()),
            ],
        ),
    ]
